version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - ./api/app:/code/app/
    environment:
      - PYTHONUNBUFFERED=1
  
  postgis:
    image: postgis/postgis:16-master  # Nom personnalisé de l'image
    container_name: geostudio_postgis
    env_file: .env
    volumes:
      - ./docker/postgis/data:/var/lib/postgresql/data  # Nom du volume personnalisé
      - ./docker/postgis/init_hstore.sql:/docker-entrypoint-initdb.d/init_hstore.sql  # Ajout du script d'initialisation
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  maputnik:
    image: maputnik/editor:latest
    container_name: maputnik
    ports:
      - "8888:8888"

  file-server:
    image: nginx:alpine
    container_name: file-server
    volumes:
      - ./test_files:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
