version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - ./api/app:/code/app/
    environment:
      - PYTHONUNBUFFERED=1
